# Generated by Django 4.0.5 on 2022-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_inputs_problem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='problem_input',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='problem_output',
        ),
        migrations.AddField(
            model_name='problems',
            name='problem_name',
            field=models.CharField(default=' ', max_length=20000),
            preserve_default=False,
        ),
    ]
