# Generated by Django 4.0.5 on 2022-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_submission_submission_oo'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_date',
            field=models.CharField(default='null', max_length=2000),
            preserve_default=False,
        ),
    ]
