# Generated by Django 4.0.5 on 2022-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_submission_submission_problemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_code',
            field=models.TextField(),
        ),
    ]
