# Generated by Django 4.0.5 on 2022-07-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_submission_submission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='username',
            field=models.CharField(default='tommy', max_length=100),
            preserve_default=False,
        ),
    ]
