# Generated by Django 4.0.5 on 2022-07-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_submission_submission_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20000)),
                ('solvedproblems', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
