# Generated by Django 4.0.5 on 2022-07-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=20000)),
                ('input_output', models.CharField(max_length=20000)),
                ('problem_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.CharField(max_length=20000)),
                ('problem_name', models.CharField(max_length=20000)),
                ('problem_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_code', models.CharField(max_length=20000)),
                ('submission_verdict', models.CharField(max_length=20000)),
                ('submission_oo', models.CharField(max_length=20000)),
            ],
        ),
    ]
